### ISSUE TITLE
error occured during installation with python 3 and  windows 8.1 64 bit 

### ISSUE THREAD

**Issue by pavanyogi** [flupke/pypotrace#16]
i have followed instructions provided here . But  installation not successful 
![screenshot 90](https://user-images.githubusercontent.com/13834016/31371505-cfa5e73a-adae-11e7-8246-26ffb1d5fcdb.png)

**Comment by LeiMazizizi** [comment]
Hi! Has anyone solved this problem? I came across this same issue...

**Comment by fiveh** [comment]
subprocess.CalledProcessError: Command '['pkg-config', '--libs', '--cflags', 'libagg']' returned non-zero exit status 1 `ubuntu 18.04 python3.6
![1](https://user-images.githubusercontent.com/12550241/54522328-fb750280-497d-11e9-9f14-af42a067e0e5.jpeg)
`

**Comment by flupke** [comment]
Hi, I don't have the ability to test on Windows unfortunately.

I recently fixed python 3 compilation issues though, maybe that can help, please have a look at #21

**Comment by sazr** [comment]
Hi has this been resolved? I get the same error on Windows 10 Python 3.7 and Python 2.7. 

> C:\Users\a>pip install pypotrace
> Collecting pypotrace
>   Using cached https://files.pythonhosted.org/packages/a8/66/3b6236524ef1f3655397ed87c08564f9e7364c6922c12f948bace59a4d96/pypotrace-0.2.tar.g
> z
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\a\AppData\Local\Temp\pip-install-peuxb1po\pypotrace\setup.py", line 4, in <module>
>         setup()
>       File "C:\Users\a\AppData\Local\Temp\pip-install-peuxb1po\pypotrace\cysetuptools.py", line 149, in setup
>         parsed_setup_cfg = parse_setup_cfg(fp, cythonize=cythonize)
>       File "C:\Users\a\AppData\Local\Temp\pip-install-peuxb1po\pypotrace\cysetuptools.py", line 222, in parse_setup_cfg
>         return _expand_cython_modules(config, cythonize, pkg_config, base_dir)
>       File "C:\Users\a\AppData\Local\Temp\pip-install-peuxb1po\pypotrace\cysetuptools.py", line 231, in _expand_cython_modules
>         pkg_config, base_dir)
>       File "C:\Users\a\AppData\Local\Temp\pip-install-peuxb1po\pypotrace\cysetuptools.py", line 239, in _expand_one_cython_module
>         _expand_pkg_config_pkgs(config, section, pkg_config)
>       File "C:\Users\a\AppData\Local\Temp\pip-install-peuxb1po\pypotrace\cysetuptools.py", line 299, in _expand_pkg_config_pkgs
>         extra_compile_args = pkg_config(pkg_names, '--cflags', env)
>       File "C:\Users\a\AppData\Local\Temp\pip-install-peuxb1po\pypotrace\cysetuptools.py", line 309, in _run_pkg_config
>         env=env).decode('utf8')
>       File "c:\users\a\appdata\local\programs\python\python37\lib\subprocess.py", line 376, in check_output
>         **kwargs).stdout
>       File "c:\users\a\appdata\local\programs\python\python37\lib\subprocess.py", line 453, in run
>         with Popen(*popenargs, **kwargs) as process:
>       File "c:\users\a\appdata\local\programs\python\python37\lib\subprocess.py", line 756, in __init__
>         restore_signals, start_new_session)
>       File "c:\users\a\appdata\local\programs\python\python37\lib\subprocess.py", line 1155, in _execute_child
>         startupinfo)
>     FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\a\AppData\Local\Temp\pip-install-peuxb1po\pypotrace\

**Comment by flupke** [comment]
Closing for no activity.
