### ISSUE TITLE
Error Installing PyPotrace on Mac OS Big Sur

### ISSUE THREAD

**Issue by AaaaronH** [flupke/pypotrace#40]
I followed the instructions to install pypotracer on my mac, but an error occurred at the final step.

Processing /Users/pokedude/Downloads/pypotrace-master
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from potrace==0.3) (1.17.0)
Building wheels for collected packages: potrace
  Building wheel for potrace (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/tmp1pi556jp
       cwd: /private/var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/pip-req-build-xh364utg
  Complete output (36 lines):
  Package libagg was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libagg.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libagg' found
  Traceback (most recent call last):
    File "/private/var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/pip-req-build-xh364utg/setup.py", line 28, in <module>
      build(setup_kwargs)
    File "/private/var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/pip-req-build-xh364utg/build.py", line 19, in build
      extra_compile_args = pkg_config("libagg", '--cflags')
    File "/private/var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/pip-req-build-xh364utg/build.py", line 11, in pkg_config
      return subprocess.check_output(["pkg-config", command, pkg_name]).decode(
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 389, in check_output
      **kwargs).stdout
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 481, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['pkg-config', '--cflags', 'libagg']' returned non-zero exit status 1.
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
      metadata_directory)
    File "/private/var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/pip-build-env-h9f48l8h/overlay/lib/python3.7/site-packages/poetry/core/masonry/api.py", line 68, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "/private/var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/pip-build-env-h9f48l8h/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 72, in make_in
      wb.build()
    File "/private/var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/pip-build-env-h9f48l8h/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 103, in build
      self._build(zip_file)
    File "/private/var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/pip-build-env-h9f48l8h/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 135, in _build
      self._run_build_command(setup)
    File "/private/var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/pip-build-env-h9f48l8h/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 169, in _run_build_command
      str(self._path / "build"),
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 341, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7', '/private/var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/pip-req-build-xh364utg/setup.py', 'build', '-b', '/private/var/folders/t1/yjb9fy9x3z753rkj68mrz97w0000gn/T/pip-req-build-xh364utg/build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for potrace
Failed to build potrace
ERROR: Could not build wheels for potrace which use PEP 517 and cannot be installed directly

I have already installed potrace with brew, but now I want to install the library for Python.

**Comment by royrwood** [comment]
I have a similar problem installing on MacOS Ventura.  Anyone have a fix?
