### ISSUE TITLE
"No module named 'potrace._potrace'" ,When I "import potrace"，this issue will arise.

### ISSUE THREAD

**Issue by MtYCNN** [flupke/pypotrace#43]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/picasso/yc7/pypotrace/potrace/__init__.py", line 1, in <module>
    from potrace._potrace import *  # NOQA
ModuleNotFoundError: No module named 'potrace._potrace'

**Comment by Riqzz** [comment]
Have you already installed it? If so, are you running `import potrace` in the pypotrace root directory?

**Comment by MtYCNN** [comment]
> If not installed, the error should not be this, but:
     No module named 'potrace‘

**Comment by Riqzz** [comment]
Yes. So you might have imported packages in this directory? I just made that mistake.

**Comment by MtYCNN** [comment]
> Yes. So you might have imported packages in this directory? I just made that mistake.

Yes, I really import  this module in this directory
