### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by DrBwts** [flupke/pypotrace#49]
Win 10, conda env with Python 3.9

`python -m pip install pypotrace`

or 

`pip install pypotrace`

I get the same error

`Collecting pypotrace
  Using cached pypotrace-0.3.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\sengnr3\.conda\envs\robo_draw\lib\site-packages (from pypotrace) (1.26.4)
Building wheels for collected packages: pypotrace
  Building wheel for pypotrace (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pypotrace (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      A setup.py file already exists. Using it.
      Traceback (most recent call last):
        File "C:\Users\sengnr3\AppData\Local\Temp\pip-install-j99yj94z\pypotrace_32cfa5f769dc490f94e5dc7173842d78\setup.py", line 28, in <module>
          build(setup_kwargs)
        File "C:\Users\sengnr3\AppData\Local\Temp\pip-install-j99yj94z\pypotrace_32cfa5f769dc490f94e5dc7173842d78\build.py", line 19, in build
          extra_compile_args = pkg_config("libagg", '--cflags')
        File "C:\Users\sengnr3\AppData\Local\Temp\pip-install-j99yj94z\pypotrace_32cfa5f769dc490f94e5dc7173842d78\build.py", line 11, in pkg_config
          return subprocess.check_output(["pkg-config", command, pkg_name]).decode(
        File "C:\Users\sengnr3\.conda\envs\robo_draw\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\sengnr3\.conda\envs\robo_draw\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\sengnr3\.conda\envs\robo_draw\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\sengnr3\.conda\envs\robo_draw\lib\subprocess.py", line 1436, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      Traceback (most recent call last):
        File "C:\Users\sengnr3\.conda\envs\robo_draw\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\sengnr3\.conda\envs\robo_draw\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\sengnr3\.conda\envs\robo_draw\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\sengnr3\AppData\Local\Temp\pip-build-env-g2pgmqmt\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 58, in build_wheel
          return WheelBuilder.make_in(
        File "C:\Users\sengnr3\AppData\Local\Temp\pip-build-env-g2pgmqmt\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "C:\Users\sengnr3\AppData\Local\Temp\pip-build-env-g2pgmqmt\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 121, in build
          self._build(zip_file)
        File "C:\Users\sengnr3\AppData\Local\Temp\pip-build-env-g2pgmqmt\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 182, in _build
          self._run_build_command(setup)
        File "C:\Users\sengnr3\AppData\Local\Temp\pip-build-env-g2pgmqmt\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 248, in _run_build_command
          subprocess.check_call([
        File "C:\Users\sengnr3\.conda\envs\robo_draw\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:/Users/sengnr3/.conda/envs/robo_draw/python.exe', 'C:\\Users\\sengnr3\\AppData\\Local\\Temp\\pip-install-j99yj94z\\pypotrace_32cfa5f769dc490f94e5dc7173842d78\\setup.py', 'build', '-b', 'C:\\Users\\sengnr3\\AppData\\Local\\Temp\\pip-install-j99yj94z\\pypotrace_32cfa5f769dc490f94e5dc7173842d78\\build', '--build-purelib', 'C:\\Users\\sengnr3\\AppData\\Local\\Temp\\pip-install-j99yj94z\\pypotrace_32cfa5f769dc490f94e5dc7173842d78\\build\\lib', '--build-platlib', 'C:\\Users\\sengnr3\\AppData\\Local\\Temp\\pip-install-j99yj94z\\pypotrace_32cfa5f769dc490f94e5dc7173842d78\\build\\lib.win-amd64-cpython-39']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pypotrace
Failed to build pypotrace
ERROR: Could not build wheels for pypotrace, which is required to install pyproject.toml-based projects`

**Comment by esyeiela** [comment]
I have the same issue, have you found the solution?

**Comment by anonymousanemone** [comment]
Also having the same issue!

**Comment by jack-ditto** [comment]
Same issue here as well.
